### PR TITLE
fix: Only the first frame from an image sequence gets included in Job Attachments

### LINKED ISSUE #213: Bug: Only the first frame from an image sequence gets included in Job Attachments
### Describe the bug

If my composition contains footage that is an image sequence instead of a video, the submitter only adds the first frame from the image sequence to the job attachments input list.

Image

### Expected Behaviour

I would expect it to grab the entire frame range that is used

Image

### Current Behaviour

Only grabs the first frame

### Reproduction Steps

Import an Image sequence (png sequence for exmaple) and then submit that comp with JobAttachments

### Environment

At minimum:
1. Windows 11 Pro
2. AE 25.3 & AE 24.6
3. Latest

Please share other details about your environment that you think might be relevant to reproducing the bug.

### PR DESCRIPTION
**Pull request by Ahuge**
Fixes: https://github.com/aws-deadline/deadline-cloud-for-after-effects/issues/213

### What was the problem/requirement? (What/Why)
Only the first frame from an image sequence gets included in Job Attachments
When you have an image sequence in your comp, it should JA the entire used sequence otherwise you get missing footage issues.

### What was the solution? (How)
Build upon the work of #207.

This updates the `findJobAttachments` function to use new logic built in `determineFootageType` and `filePathsFromFootageItem`

`determineFootageType` is a helper method used to determine the type of footage referenced. This was required because there is no native method in AE to determine if the FootageItem is an ImageSequence or Video.

`filePathsFromFootageItem` utilizes that function to implement logic against the ImageSequence footage items and gather all images in the folder from that sequence.
It takes inspiration from the `Smart Import.jsx` for resolving sequences with added logic around it to ensure that the files are part of the same sequence.
In addition to this, the function will gather the file paths starting from the first frame imported and only for the length of the FootageItem. The idea is that hopefully if your image sequence starts at frame 002 for example and is only used for 10 frames, we only upload the portion of the image sequence files on disk that are actually used in the comp.

This PR is built on top of #207 so the raw lines of code look higher until that PR is merged.
See [Ahuge - #30](https://github.com/Ahuge/deadline-cloud-for-after-effects/pull/30) for a PR of just the two branches in my repo
### What is the impact of this change?
Additional input files in the Job Attachments screen if the composition uses Image Sequences.

### How was this change tested?
- [X] Testing using SMF from a Windows AE 25.3 client.
- [x] Tested using SMF from a MacOS AE 25.3 client
- [x] Testing using SMF from a Windows AE 24.6 client.
- [x] Tested using SMF from a MacOS AE 24.6 client
#### If you modified source files, did you run the Python script to update the files under the dist folder?
Yes

### Was this change documented?
Not documented as this fixes functionality that the user expected to exist

### Is this a breaking change?
I don't believe so. This corrects functionality that was missing.

#### Before:
Job Attachments Before

#### After
Job Attachments After

---

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by eherozhao — COMMENTED** [review]
A way to make this CR not depending on the other ongoing PRs is to create a separate branch based on mainline for this feature dev. That can help reviewers focus on the real changes. If it is an easy switch, do you mind move the changes to a new branch and raise it up?

**Comment by Ahuge** [comment]
Rebased off of mainline so you just see this PR

**Comment by olly-glenn-arch** [comment]
For now I've rebased this off of #207 so that when #207 gets merged rebasing this branch off of mainline shouldn't be too messy. Just tested on Windows with Aftereffects 24.6.7, 25.1.0, and 25.2.2, and frame sequences rendered as expected. I've attached a more detailed breakdown of the tests I ran:

[_TESTING_NOTES.txt](https://github.com/user-attachments/files/21647335/_TESTING_NOTES.txt)

**Comment by olly-glenn-arch** [comment]
Tested and working on AE 24.6.7, 25.1.0, and 25.2.2 on Windows, will test on Mac tomorrow.

File: src/utils/Utils.jsx [hunk 1]
```diff
@@ -66,6 +66,15 @@ if (typeof DEFAULT_MAX_CPU_USAGE_PERCENTAGE === "undefined") {
...
 }
 
+var FootageTypes = {
+    Image: 0,
+    ImageSequence: 1,
+    Video: 2,
+    Audio: 3,
+    Unknown: 4
+}
+var ImageExtensionRegex = /(ai|bmp|bw|cin|cr2|crw|dcr|dng|dib|dpx|eps|erf|exr|gif|hdr|icb|iff|jpe|jpeg|jpg|mos|mrw|nef|orf|pbm|pef|pct|pcx|pdf|pic|pict|png|ps|psd|pxr|raf|raw|rgb|rgbe|rla|rle|rpf|sgi|srf|tdi|tga|tif|tiff|vda|vst|x3f|xyze)/i;
```
Comment (viknith) [inline src/utils/Utils.jsx]: These are a lot of image extension types. Have you confirmed that all of them are supported for rendering on After Effects? I recall there are customers with their own custom image or video type that expect to render on After Effects. What would the user experience be here if they provide an image sequence that doesn't match this regex? Do we need to surface a warning or an info popup about it?

File: dist/DeadlineCloudSubmitter.jsx [hunk 2]
```diff
@@ -559,6 +568,65 @@ function __generateUtil() {
...
+        var regex = /^(.*?)(\d*)(\D*?)$/;
+        var match = fileName.match(regex);
+        return {
+            prefix: match[1],
+            frame: parseInt(match[2], 10),
+            suffix: match[3]
+        }
+    }
+
+    function filePathsFromFootageItem(footageItem) {
```
Comment (viknith) [inline dist/DeadlineCloudSubmitter.jsx]: Nit: rename to getFilePathsFromFootageItem

File: src/utils/Utils.jsx [hunk 3]
```diff
@@ -555,6 +564,65 @@ function __generateUtil() {
...
+     * Extracts image 
+     * @param {string} fileName 
+     * @returns Object containing prefix, name, and suffix 
+     */
+    function getImageSequenceInformation(fileName) {
+        var regex = /^(.*?)(\d*)(\D*?)$/;
+        var match = fileName.match(regex);
+        return {
+            prefix: match[1],
+            frame: parseInt(match[2], 10),
```
Comment (viknith) [inline src/utils/Utils.jsx:610]: Does this represent the number of frames? If so, renaming to frameCount or numberOfFrames would probably be better, thoughts?

File: src/utils/Utils.jsx (hunk 1 above)
Comment (olly-glenn-arch) [reply src/utils/Utils.jsx]: Aftereffects doesn't differentiate between image sequences and video files when importing video footage, so this regex is necessary to figure out whether a video is an image sequence or not. Currently, the way the type of footage is determined is that we first query whether the source is a still image, and if it's not a still image then we check whether the file has one of these extensions to determine if it's an image sequence or video file (an image sequence is just non-still footage that has an image file extension). The ExtendScript API is very restrictive here so I'm not sure if there's any other way of doing it. The list of supported image file extensions is taken from here: https://helpx.adobe.com/after-effects/kb/supported-file-formats.html

If a user provides an image sequence that doesn't match this regex that means it's in an unsupported file format so the project theoretically should have broken before we got to this step. If a customer is using a proprietary image format / video codec then there would be no easy way for us to determine whether it was a still image sequence or video file (again because in ExtendScript there is no differentiation between the two) and supporting that case may fall outside the scope of this PR. It's also possible that the in-house image formats that customers are using are just extended versions of existing formats that share the same file extensions--do you have any examples of custom image file formats / video containers/codecs that customers are using? As long as the file extensions are in Adobe's list of supported extensions it should work fine.

File: dist/DeadlineCloudSubmitter.jsx (hunk 2 above)
Comment (olly-glenn-arch) [reply dist/DeadlineCloudSubmitter.jsx]: Done

File: src/utils/Utils.jsx (hunk 3 above)
Comment (olly-glenn-arch) [reply src/utils/Utils.jsx:610]: No, each of these objects represents an individual frame. Updated comment to clarify

File: dist/DeadlineCloudSubmitter.jsx [hunk 4]
```diff
@@ -559,6 +568,65 @@ function __generateUtil() {
...
+        return FootageTypes.Unknown
+    }
+
+    /**
+     * Extracts frame number, prefix, and suffix for single frame in image sequence.
+     * @param {string} fileName 
+     * @returns Object containing prefix, name, and suffix 
+     */
+    function getImageSequenceInformation(fileName) {
+        var regex = /^(.*?)(\d*)(\D*?)$/;
```
Comment (viknith) [inline dist/DeadlineCloudSubmitter.jsx]: Security hotspot finding: https://sonarcloud.io/project/security_hotspots?id=aws-deadline_deadline-cloud-for-after-effects&pullRequest=214&hotspots=AZi-mbtK4c14mioZB6lB

Comment (olly-glenn-arch) [reply dist/DeadlineCloudSubmitter.jsx]: It looks like the problem sonar is having here is that slow regex operations can create vulnerabilities for DDoS attacks. I updated the regex to make the last operator greedy instead of lazy which should help with performance, but the first operator has to be lazy because otherwise it would just match the entire string every time. Also, considering that this is running locally on the user's machine, I don't think a DDoS attack is something we'd need to worry about..

**Comment by olly-glenn-arch** [comment]
Just tested on supported version of AE on both Windows and Mac and image sequence job attachments are being uploaded correctly, if there are no other changes to be made this should be ready to merge.

**Review by viknith — DISMISSED** [review]

File: dist/DeadlineCloudSubmitter.jsx [hunk 5]
```diff
@@ -70,6 +70,15 @@ if (typeof DEFAULT_MAX_CPU_USAGE_PERCENTAGE === "undefined") {
...
 }
 
+var FootageTypes = {
+    Image: 0,
+    ImageSequence: 1,
+    Video: 2,
+    Audio: 3,
+    Unknown: 4
+}
+var ImageExtensionRegex = /(ai|bmp|bw|cin|cr2|crw|dcr|dng|dib|dpx|eps|erf|exr|gif|hdr|icb|iff|jpe|jpeg|jpg|mos|mrw|nef|orf|pbm|pef|pct|pcx|pdf|pic|pict|png|ps|psd|pxr|raf|raw|rgb|rgbe|rla|rle|rpf|sgi|srf|tdi|tga|tif|tiff|vda|vst|x3f|xyze)/i;
```
Comment (eherozhao) [inline dist/DeadlineCloudSubmitter.jsx]: https://github.com/aws-deadline/deadline-cloud-for-after-effects/blob/mainline/src/submission/JobTemplateHelper.jsx#L463 we have already had a similiar method why not just use it?

Comment (olly-glenn-arch) [reply dist/DeadlineCloudSubmitter.jsx]: Good point, I'll switch to that method and also update it to include all of the image outputs that AE supports

Comment (olly-glenn-arch) [reply dist/DeadlineCloudSubmitter.jsx]: Done

**Comment by olly-glenn-arch** [comment]
Tested again and ready for review

**Review by viknith — APPROVED** [review]

**Review by viknith — DISMISSED** [review]

File: dist/DeadlineCloudSubmitter.jsx [hunk 6]
```diff
@@ -559,6 +567,81 @@ function __generateUtil() {
...
+    // Return the `FootageTypes` value for the passed footageItem
+    function determineFootageType(footageItem) {
+        if (footageItem.hasVideo) {
+            var filePath = File.decode(footageItem.mainSource.file);
+            var extension = filePath.substr(filePath.lastIndexOf(".") + 1, filePath.length).toLowerCase();
+            if (footageItem.mainSource.isStill) {
+                return FootageTypes.Image
+            } else if (isImage(extension)) {
+                return FootageTypes.ImageSequence
+            } else {
```
Comment (jaikish) [inline dist/DeadlineCloudSubmitter.jsx:595]: Should we check `isVideo` here?

Comment (olly-glenn-arch) [reply dist/DeadlineCloudSubmitter.jsx:595]: This line of code is only reached if `footageItem.hasVideo` is true, so we already know that the footage item is a video. However, since AE considers both image sequences and still images to be special types of videos, we have to double-check the file extension to figure out if the video is actually a still or image sequence instead. If it isn't a still or image sequence, then it's a normal video.

**Review by jaikish — APPROVED** [review]

**Review by eherozhao — APPROVED** [review]
