### PR TITLE
fix: added UTF-8 file encoding support on all files written to or read from

### LINKED ISSUE #113: Bug: Special Characters cause issues/
### Describe the bug

Files with special character ( e.g. with "ñ" in the name) cause errors on submission.

### Expected Behaviour

I believe these character sets ( utf-8) should be supported.

### Current Behaviour

Error.

### Reproduction Steps

Submit a scene with a special character in the name.

### Environment

At minimum:
1. Operating system (e.g. Windows Server 2022; macOS Sequoia 15.1.1; etc.)
2. Version of After Effects
3. Version of this package

Please share other details about your environment that you think might be relevant to reproducing the bug.

### PR DESCRIPTION
**Pull request by viknith**
### What was the problem/requirement? (What/Why)
Files with special characters were not being processed correctly. See #113 for more info.

### What was the solution? (How)
Ensure that every file being read from and/or written to that is submitted or used for job bundle are set to UTF-8 encoding. Resolves #113 

### What is the impact of this change?
Characters like ñ are now supported and won't break the AE job submission.

### How was this change tested?
MacOS AE25 and Windows AE25 job submission, verified that the job template does pop up with the correct job attachment paths and the resulting job bundle JSON files do not have the missing character emoji.
Screenshot 2025-01-31 at 3 22 35 PM
Screenshot 2025-01-31 at 3 22 14 PM

### Was this change documented?

No need

- Did you update all relevant docstrings for functions that you modified?
No need

- Should the README.md, DEVELOPMENT.md, or other documents in the repository's docs/ directory be updated along with your change?

No need

### Is this a breaking change?
No

---

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by crowecawcaw — DISMISSED** [review]

**Review by eng-josh — APPROVED** [review]

**Review by NathanMacLeod — APPROVED** [review]

**Review by npmacl — APPROVED** [review]

File: dist/DeadlineCloudSubmitter.jsx [hunk 1]
```diff
@@ -1532,7 +1540,7 @@ function SubmitSelection(selection, framesPerTask) {
             sanitizedOutputFolder
         );
         var assetReferencesOutDir = bundlePath + "/asset_references.json";
-        writeJSONFile(jobAttachmentsContents, assetReferencesOutDir);
+        writeFile(assetReferencesOutDir, JSON.stringify(jobAttachmentsContents));
```
Comment (eherozhao) [inline dist/DeadlineCloudSubmitter.jsx:1543]: I think we deleted two argument (null, 4). What are the intentation of the new files?

Comment (viknith) [reply dist/DeadlineCloudSubmitter.jsx:1543]: Ah I missed this, let me fix it.

Comment (viknith) [reply dist/DeadlineCloudSubmitter.jsx:1543]: null, 4 just makes the files prettier to look at. Without it, it would look uglier. I'll put up a chore PR to fix it.
