### PR TITLE
fix: repaired getTempFolder() function logic

### LINKED ISSUE #196: Bug: Submit button fails in After Effects 2025.1 with DeadlineCloudSubmitter-2025.05.27.0 due to invalid temp directory
### Describe the bug

When trying to submit a render job from After Effects 2025.1 using the DeadlineCloudSubmitter-2025.05.27.0 (Downloaded from the AWS Deadline Cloud Console), the plugin throws the following error:

Error: No valid temporary directory found. Check permissions to one of these paths:
C:\Users\ADMINI~1\AppData\Local\Temp\2,
C:\Users\Administrator\AppData\Roaming\DeadlineCloudAETemp,
C:\Users\Administrator\Documents\DeadlineCloudAETemp

All listed directories already exist and have full read/write permissions assigned to the Administrator user. Despite this, the submit action fails and the expected “Submit to AWS Deadline Cloud” dialog does not appear.

Image

### Expected Behaviour

Clicking the Submit button should launch the “Submit to AWS Deadline Cloud” window with populated job settings, as it did in the previous version of the script.

### Current Behaviour

Clicking the Submit button results in a blocking error dialog stating that no valid temporary directory was found, even though all referenced directories are valid and accessible with proper permissions.

### Reproduction Steps

1. Launch After Effects 2025.1.0 or 25.2.2
2. Load any `.aep` project with a comp ready for render.
3. Go to Window > DeadlineCloudSubmitter.jsx.
4. Select a comp from the list.
5. Set output path and frame range.
6. Click Submit.
7. Observe the error dialog.

### Environment

- Operating System: Windows Server 2025 
- After Effects Version: 2025.1.0 and 2025.2.2
- DeadlineCloudSubmitter Version: 2025.05.27.0

### PR DESCRIPTION
**Pull request by viknith**
Fixes: https://github.com/aws-deadline/deadline-cloud-for-after-effects/issues/196, errors with submitter not working

### What was the problem/requirement? (What/Why)
Recently we rolled out a change to support alternative temp folders to use in case the submitter user is using a hardened machine with locked down permissions. However, there were a collection of bugs in this code change that were not caught and needed to be fixed.

### What was the solution? (How)
- Fix the for-looping logic since it should be `for-of` not `for-in` for array-based looping.
- Fix the incorrect `if` check on folder error
- Fix the incorrect `if` check on folder creation
- Remove code to clear the contents of the temp folder, no need to do this every time. 

### What is the impact of this change?
Restores ability to submit jobs with the AE submitter.

### How was this change tested?
- [x] AE 25 on Mac
- [x] AE 24 on Mac
- [x] AE 25 on Windows
- [x] AE 24 on Windows

#### If you modified source files, did you run the Python script to update the files under the dist folder?
Yes

#### If you modified the `/installer`, `/install_builder`, or `/scripts` logic, please run the integration tests and paste the results below
N/A

### Was this change documented?
No, no need.

### Is this a breaking change?
No, this is a fix.

---

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by jaikish — APPROVED** [review]

File: src/utils/Utils.jsx [hunk 1]
```diff
@@ -353,30 +353,25 @@ function __generateUtil() {
...
             }
 
-            //List all files and check for errors
-            //Not having list permissions is a common source of errors
-            var existingFiles = folder.getFiles();
-            if (!folder.error) {
+            // List all files and check for errors
+            // Not having list permissions is a common source of errors
+            folder.getFiles();
+            if (folder.error) {
```
Comment (eherozhao) [inline src/utils/Utils.jsx:369]: nit: should we log this error?

**Review by eherozhao — APPROVED** [review]
