### PR TITLE
fix: added Python validation check on job submission

### LINKED ISSUE #153: Bug: Submitter silently fails if python is not installed
### Describe the bug

When submitting from a machine that doesn't have a python installation, the submit button brings up a command prompt window that disappears a split second later. No error is present.

### Expected Behaviour

We should at the very least show an error. In this case, the submitter was installed with the installer from the Deadline Cloud downloads page, so it should have also handled installing python for us if possible.

### Current Behaviour

A command prompt window briefly flashes.

### Reproduction Steps

Spin up a new Windows machine and install After Effects on it. Run the Deadline Cloud submitter installer. Try to submit.

### Environment

At minimum:
1. Operating system: Windows
2. Version of After Effects: 2025
3. Version of this package: The version available in DeadlineCloudSubmitter-2025.02.06.0-windows-x64-installer.exe

Please share other details about your environment that you think might be relevant to reproducing the bug.

### PR DESCRIPTION
**Pull request by viknith**
Fixes: https://github.com/aws-deadline/deadline-cloud-for-after-effects/issues/153

### What was the problem/requirement? (What/Why)
Customers were reporting that they were not getting proper error messaging when Python was not installed or added to PATH

### What was the solution? (How)
Added additional python validation check on job submission so that job submission cannot proceed and fails early until it is validated that Python is installed and added to the customer's PATH env variable. This prevents having to add duplicate python validation in other places and centralizes it in one area.

### What is the impact of this change?
Better error handling and messaging for customers

### How was this change tested?
Updated the scripts in AE, uninstalled Python, then attempted to submit a job, and verified the popup appeared. Then I reinstalled Python and added it to my PATH and attempted job submission, which passed!

#### If you modified source files, did you run the Python script to update the files under the dist folder?
N/A

#### If you modified the `/installer`, `/install_builder`, or `/scripts` logic, please run the integration tests and paste the results below
N/A

#### If `installer/` was modified or a file was added/removed from `dist/`, then update the installer tests and post the test results below
N/A

### Was this change documented?
No

### Is this a breaking change?
No

---

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

File: dist/DeadlineCloudSubmitter.jsx [hunk 1]
```diff
@@ -2412,13 +2412,15 @@ function buildUI(thisObj) {
...
-            maxCpuUsagePercentage = parseInt(maxCpuUsagePercentageTextBox.text)
+        if (getPythonExecutable()) {
+            const multiFrameRendering = mfrCheckBox.value ? "ON" : "OFF";
+            var maxCpuUsagePercentage = undefined;
+            if (mfrCheckBox.value) {
+                maxCpuUsagePercentage = parseInt(maxCpuUsagePercentageTextBox.text)
+            }
+            SubmitSelection(list.selection, parseInt(framesPerTaskTextBox.text), multiFrameRendering, maxCpuUsagePercentage);
+            list.selection = null;
         }
```
Comment (eherozhao) [inline dist/DeadlineCloudSubmitter.jsx:2423]: If we would like to do this check, I think we should throw the error in a else block to notify customers that their python executable is not set as expected and pointing them to any possible reference to unblock the issue.

Comment (viknith) [reply dist/DeadlineCloudSubmitter.jsx:2423]: The error message happens in the getPythonExecutable function call

Comment (viknith) [reply dist/DeadlineCloudSubmitter.jsx:2423]: The getPythonExectuable function has error handling built into that because it's used in other places.

**Review by npmacl — APPROVED** [review]

**Review by eherozhao — APPROVED** [review]
